### ISSUE TITLE
FR-T5.3-6: xOpera should support all available TOSCA policy type keywords

### ISSUE THREAD

**Issue by anzoman** [radon-h2020/radon-delivery-toolchain#38]
ID: | FR-T5.3-6
-- | --
Type: | USABILITY
User story: | A lot of users use TOSCA Policy Types which are a logical grouping of TOSCA nodes that use an implicit relationship and need to be managed together during the orchestration process in order to give some result. To exploit the policies to their full potential users would desire to be able to use all the supported keywords for policies along with the TOSCA orchestrator.
Requirement: | As of now xOpera orchestration tool does include the support for policies so it is possible to declare TOSCA policy definition inside the `topology_template` section of the TOSCA or a separate policy type definition in `policy_types` section of the service template but there is currently no support for policy targets and triggers.
Extended Description: | The first thing that would need to be done is to updating the opera's TOSCA parser to add the support for policy type targets (which represents an optional list of valid node types or group types the policy type can be applied to) and the second step would feature adding support for triggers and trigger events definitions.
Priority: | Could have
Affected Tools: | DELIVERY_TOOLCHAIN, ORCHESTRATOR
Means of Verification: | Try to deploy a service template with policy type that uses targets and triggers.

Looking into TOSCA YAML v1.3 policy type definition has the following keywords: 

```yaml
<policy_name>:
  type: <policy_type_name>
  description: <policy_description>
  metadata:
    <map of string>
  properties:
    <property_assignments>
  targets: [<list_of_policy_targets>]
  triggers:
    <trigger_definitions>
```
